// One-time backfill for the 48 words generated by the 2026-08-22 volume test
// batch (scripts/generate-flagship-batch.ts), run before the quote-length
// fix landed (extractSnippet was capping at 300 chars instead of ~20 words,
// and Nerthus/kaikki quotes bypassed length capping entirely -- see
// src/lib/corpus-search.ts and src/lib/sourcing-tier.ts).
//
// Only touches eras whose quote_source_url is non-null -- that's the
// signal a quote came from local corpus/kaikki evidence (findLocalEvidence),
// not a live-fetch/model-authored quote (flagship.ts leaves quoteSourceUrl
// null in that branch). Re-running findLocalEvidence is a pure local DB
// operation -- no Anthropic API calls, no cost.

import { and, eq, gte } from "drizzle-orm";
import { db } from "../src/db";
import { flagshipEras, flagshipWords } from "../src/db/schema";
import { findLocalEvidence } from "../src/lib/sourcing-tier";

const BATCH_CUTOFF = "2026-08-22T00:00:00Z";

async function main() {
  const recentWords = await db
    .select({ id: flagshipWords.id, headword: flagshipWords.headword })
    .from(flagshipWords)
    .where(gte(flagshipWords.createdAt, new Date(BATCH_CUTOFF)));

  console.log(`Found ${recentWords.length} words from the volume-test batch.`);

  let checked = 0;
  let updated = 0;
  let unchanged = 0;
  let noEvidence = 0;

  for (const word of recentWords) {
    const eras = await db
      .select()
      .from(flagshipEras)
      .where(and(eq(flagshipEras.flagshipWordId, word.id)));

    for (const era of eras) {
      if (!era.quoteSourceUrl) continue; // model-authored/live-fetch quote, not locally sourced -- skip
      checked++;

      const fresh = await findLocalEvidence(era.era, era.form, word.headword);
      if (!fresh) {
        console.log(`  WARN ${word.headword} (${era.era}): no local evidence found on re-check`);
        noEvidence++;
        continue;
      }

      if (
        fresh.quote === era.quote &&
        fresh.quoteCitation === era.quoteCitation &&
        fresh.quoteTranslation === era.quoteTranslation
      ) {
        unchanged++;
        continue;
      }

      await db
        .update(flagshipEras)
        .set({
          quote: fresh.quote,
          quoteCitation: fresh.quoteCitation,
          quoteTranslation: fresh.quoteTranslation,
          quoteSourceUrl: fresh.quoteSourceUrl,
        })
        .where(eq(flagshipEras.id, era.id));

      const oldLen = era.quote?.split(/\s+/).length ?? 0;
      const newLen = fresh.quote?.split(/\s+/).length ?? 0;
      console.log(`  ok   ${word.headword} (${era.era}): ${oldLen} words -> ${newLen} words`);
      updated++;
    }
  }

  console.log(
    `\nDone. ${checked} locally-sourced eras checked: ${updated} updated, ${unchanged} already fine, ${noEvidence} no evidence found.`,
  );
  process.exit(0);
}

main();
